units:
  visual_x: 17.5
  visual_y: 16.5
  mod_x_width: 1.25u-1.05
  space_width: 2.25u-1.05
  px: cx + 4
  py: cy + 4

  # Stabalizer cutout
  u: U
  stabilizer_width: 7
  stabilizer_height: 14
  stabilizer_offset: -1 # This means south stabs, use `orient` to rotate them for north facing scenarios
  stabilizer_spacing_2u: u / 2 + stabilizer_width / 2 + ((23.8 / 2) - (14 / 2) - (stabilizer_width / 2)) # The complex formula has two magic numbers. 14 is the size of a switch cutout for a plate. 23.8 is the distance between each stabilizer on a 2-2.75u stabilizer, as specified by Cherry

points:
  zones:
    # LEFT SIDE ZONES
    left_matrix:
      anchor:
        shift: [100, -100]
      columns:
        one:
          key:
            column_mark: 1
            column_net: P01
        two:
          key:
            column_mark: 2
            column_net: P02
        three:
          key:
            column_mark: 3
            column_net: P03
        four:
          key:
            column_mark: 4
            column_net: P04
        five:
          key:
            column_mark: 5
            column_net: P05
        six:
          key:
            column_mark: 6
            column_net: P06
      rows:
        bottom:
          row_net: P07
        home:
          row_net: P08
        top:
          row_net: P09
        num:
          row_net: P10
    
    left_modrow:
      anchor:
        shift: [100, -100-u]
      columns:
        ctrl:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)/2, 0]
            column_mark: 1
            column_net: P01
        super:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(3/2), 0]
            column_mark: 2
            column_net: P02
        alt:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(5/2), 0]
            column_mark: 3
            column_net: P03
        space:
          key:
            width: space_width
            shift: [space_width-0.82u, 0]
            column_mark: 5
            column_net: P05
      rows:
        modrow:
          row_net: P11

    # RIGHT SIDE ZONES
    right_matrix:
      anchor:
        shift: [100, -180]
      columns:
        one:
          key:
            column_mark: 1
            column_net: P01
        two:
          key:
            column_mark: 2
            column_net: P02
        three:
          key:
            column_mark: 3
            column_net: P03
        four:
          key:
            column_mark: 4
            column_net: P04
        five:
          key:
            column_mark: 5
            column_net: P05
        six:
          key:
            column_mark: 6
            column_net: P06
        seven:
          key:
            column_mark: 7
            column_net: P07
        eight:
          key:
            column_mark: 8
            column_net: P08
      rows:
        top:
          row_net: P10
        num:
          row_net: P09

    right_enterrow:
      anchor:
        shift: [100, -180-u]
      columns:
        one:
          key:
            column_mark: 1
            column_net: P01
        two:
          key:
            column_mark: 2
            column_net: P02
        three:
          key:
            column_mark: 3
            column_net: P03
        four:
          key:
            column_mark: 4
            column_net: P04
        five:
          key:
            column_mark: 5
            column_net: P05
        six:
          key:
            column_mark: 6
            column_net: P06
        enter:
          key:
            shift: [0.5u, 0]
            width: 2u-1
            column_mark: 7
            column_net: P07
      rows:
        home:
          row_net: P11

    right_bottomrow:
      anchor:
        shift: [100, -180-2u]
      columns:
        one:
          key:
            column_mark: 1
            column_net: P01
        two:
          key:
            column_mark: 2
            column_net: P02
        three:
          key:
            column_mark: 3
            column_net: P03
        four:
          key:
            column_mark: 4
            column_net: P04
        five:
          key:
            column_mark: 5
            column_net: P05
        six:
          key:
            column_mark: 6
            column_net: P06
        seven:
          key:
            column_mark: 7
            column_net: P07
        eight:
          key:
            column_mark: 8
            column_net: P08
      rows:
        bottom:
          row_net: P12

    right_modrow:
      anchor:
        shift: [100, -180-3u]
      columns:
        space:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(1/2), 0]
            column_mark: 5
            column_net: P01
            spread: 23.8125
        ctrl:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(3/2), 0]
            column_mark: 1
            column_net: P02
        super:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(5/2), 0]
            column_mark: 2
            column_net: P03
        alt:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(7/2), 0]
            column_mark: 3
            column_net: P04
        left_arrow:
          key:
            shift: [u, 0]
            column_mark: 4
            column_net: P05
        down_arrow:
          key:
            shift: [u, 0]
            column_mark: 5
            column_net: P06
        right_arrow:
          key:
            shift: [u, 0]
            column_mark: 6
            column_net: P07
      rows:
        modrow:
          row_net: P13

outlines:
  # LEFT SIDE OUTLINES
  left_2u_stabilizer:
    - operation: stack
      where: left_modrow_space_modrow
      what: rectangle
      size: [stabilizer_width, stabilizer_height]
      adjust:
        shift: [stabilizer_spacing_2u, stabilizer_offset]
    - operation: stack
      where: left_modrow_space_modrow
      what: rectangle
      size: [stabilizer_width, stabilizer_height]
      adjust:
        shift: [-stabilizer_spacing_2u, stabilizer_offset]
  left_raw:
    - what: rectangle
      where: true
      asym: left
      size: [1cx,1cy]
  left_keys:
    - what: rectangle
      where: true
      size: [cx-0.5, cy-0.5]
  left_keys_w_stabs:
    - name: left_keys
    - operation: add
      name: left_2u_stabilizer
  left_board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: left_matrix_one_num
          shift: [-1.75px, 0.6py]
        - ref: left_matrix_six_num
          shift: [0.5px, 0.6py]
        - ref: left_matrix_six_bottom
          shift: [0.5px, -1u - 0.6py]
        - ref: left_modrow_ctrl_modrow
          shift: [-1.875px,-0.6py]
  left_combo:
    - name: left_board
    - operation: subtract
      name: left_keys_w_stabs
  
  # RIGHT SIDE OUTLINES
  right_2u_stabilizer:
    - operation: stack
      where: right_enterrow_enter_home
      what: rectangle
      size: [stabilizer_width, stabilizer_height]
      adjust:
        shift: [stabilizer_spacing_2u, stabilizer_offset]
    - operation: stack
      where: right_enterrow_enter_home
      what: rectangle
      size: [stabilizer_width, stabilizer_height]
      adjust:
        shift: [-stabilizer_spacing_2u, stabilizer_offset]
  right_raw:
    - what: rectangle
      where: true
      asym: right
      size: [1cx,1cy]
  right_keys:
    - what: rectangle
      where: true
      size: [cx-0.5, cy-0.5]
  right_keys_w_stabs:
    - name: right_keys
    - operation: add
      name: right_2u_stabilizer
  right_board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: right_matrix_one_num
          shift: [-0.5px, 0.6py]
        - ref: right_matrix_eight_num
          shift: [1.75px, 0.6py]
        - ref: right_modrow_right_arrow_modrow
          shift: [1.75px, -0.6py]
        - ref: right_modrow_space_modrow
          shift: [-0.61px, -0.6py]
  right_combo:
    - name: right_board
    - operation: subtract
      name: right_keys_w_stabs

pcbs:
  # No MCU, it will be added later in kicad
  aurora_l:
    outlines:
      main:
        outline: left_board
    footprints:
      mx-hotswap:
        what: mx
        where: /^left_/
        params:
          from: "{{colrow}}"
          to: "{{column_net}}"
          keycaps: true
          hotswap: true
      diode:
        what: diode
        where: /^left_/
        adjust:
          rotate: 0
          shift: [ 0, -10 ]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      rgb_led:
        what: WS2812-2020
        where: [/^(left_matrix_.*_num).*/, /^(left_matrix_.*_home).*/, /^(left_modrow).*/, /^(left_matrix_.*_top).*/, /^(left_matrix_.*_bottom).*/]
        adjust:
          shift: [ 0, -5 ]
        params:
          din: "P010"
          vcc: "VCC"
          dout: "P009"
          gnd: "GND"
      powerswitch:
        what: slider
        where:
          ref: left_matrix_one_home
          rotate: 90
          shift: [-1.92u, 0.5u]
        params:
          from: RAW
          to: BAT
          side: B
      jstph:
        what: jstph
        where:
          ref: left_matrix_one_home
          shift: [-1.5u, 0.75u]
          rotate: 270
        params:
          pos: BAT
          neg: GND
          side: B
      hole_top_left:
        what: mountinghole
        where:
          ref: left_matrix_one_num
          shift: [0.5u, -0.5u]
      hole_top_right:
        what: mountinghole
        where:
          ref: left_matrix_six_num
          shift: [-0.5u, -0.5u]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: left_matrix_one_home
          shift: [0.5u, -0.5u]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: left_matrix_six_home
          shift: [-0.5u, -0.5u]
  
  aurora_r:
    outlines:
      main:
        outline: right_board
    footprints:
      mx-hotswap:
        what: mx
        where: /^right_/
        params:
          from: "{{colrow}}"
          to: "{{column_net}}"
          keycaps: true
          hotswap: true
      diode:
        what: diode
        where: /^right_/
        adjust:
          rotate: 0
          shift: [ 0, -10 ]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      rgb_led:
        what: WS2812-2020
        where: [/^(right_matrix_.*_num).*/, /^(right_enterrow_.*_home).*/, /^(right_modrow_.*_modrow).*/, /^(right_matrix_.*_top).*/, /^(right_bottomrow_.*_bottom).*/]
        adjust:
          shift: [ 0, -5 ]
        params:
          din: "P010"
          vcc: "VCC"
          dout: "P009"
          gnd: "GND"
      rotary:
        what: rotary
        params:
          A: P006
          C: GND
          B: P008
          from: P002
          to: P017
        where:
          ref: right_matrix_eight_top
          shift: [1.4u, -1u]
      powerswitch:
        what: slider
        where:
          ref: right_matrix_eight_top
          rotate: 270
          shift: [1.92u, 0.5u]
        params:
          from: RAW
          to: BAT
          side: B
      jstph:
        what: jstph
        where:
          ref: right_matrix_eight_top
          shift: [1.5u, 0.5u]
          rotate: 90
        params:
          pos: BAT
          neg: GND
          side: B
      hole_top_left:
        what: mountinghole
        where:
          ref: right_matrix_one_num
          shift: [0.5u, -0.5u]
      hole_top_right:
        what: mountinghole
        where:
          ref: right_matrix_eight_num
          shift: [-0.5u, -0.5u]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: right_bottomrow_one_bottom
          shift: [0.5u, 0.5u]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: right_bottomrow_eight_bottom
          shift: [-0.5u, -0.5u]

cases:
  top_plate:
    - name: left_combo
      extrude: 1.2
    - name: right_combo
      extrude: 1.2
