
units:
  visual_x: 17.5
  visual_y: 16.5
  mod_x_width: 1.25u-1.05
  px: cx + 4
  py: cy + 4
  

  # Stabalizer cutout
  u: U # Ensure we are using 19.05!
  stabilizer_width: 7
  stabilizer_height: 14
  stabilizer_offset: -1 # This means south stabs, use `orient` to rotate them for north facing scenarios
  stabilizer_spacing_2u: u / 2 + stabilizer_width / 2 + ((23.8 / 2) - (14 / 2) - (stabilizer_width / 2)) # The complex formula has two magic numbers. 14 is the size of a switch cutout for a plate. 23.8 is the distance between each stabilizer on a 2-2.75u stabilizer, as specified by Cherry

points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      columns:
        one:
          key:
            column_mark: 1
            column_net: P106
        two:
          key:
            column_mark: 2
            column_net: P104
        three:
          key:
            column_mark: 3
            column_net: P011
        four:
          key:
            column_mark: 4
            column_net: P100
        five:
          key:
            column_mark: 5
            column_net: P024
        six:
          key:
            column_mark: 6
            column_net: P022
        seven:
          key:
            column_mark: 7
            column_net: P020
        eight:
          key:
            column_mark: 8
            column_net: P017
      rows:
        top:
          row_net: P029
        num:
          row_net: P031

    enterrow:
      anchor:
        shift: [100, -100-u]
      columns:
        one:
          key:
            column_mark: 1
            column_net: P106
        two:
          key:
            column_mark: 2
            column_net: P104
        three:
          key:
            column_mark: 3
            column_net: P011
        four:
          key:
            column_mark: 4
            column_net: P100
        five:
          key:
            column_mark: 5
            column_net: P024
        six:
          key:
            column_mark: 6
            column_net: P022
        enter:
          key:
            shift: [0.5u, 0]
            width: 2u-1
            column_mark: 7
            column_net: P020
      rows:
        home:
          row_net: P002

    bottomrow:
      anchor:
        shift: [100, -100-2u]
      columns:
        one:
          key:
            column_mark: 1
            column_net: P106
        two:
          key:
            column_mark: 2
            column_net: P104
        three:
          key:
            column_mark: 3
            column_net: P011
        four:
          key:
            column_mark: 4
            column_net: P100
        five:
          key:
            column_mark: 5
            column_net: P024
        six:
          key:
            column_mark: 6
            column_net: P022
        seven:
          key:
            column_mark: 7
            column_net: P020
        eight:
          key:
            column_mark: 8
            column_net: P017
      rows:
        bottom:
          row_net: P115

    modrow:
      anchor:
        shift: [100, -100-3u]
      columns:
        space:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(1/2), 0]
            column_mark: 5
            column_net: P106
            spread: 23.8125
        ctrl:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(3/2), 0]
            column_mark: 1
            column_net: P104
        super:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(5/2), 0]
            column_mark: 2
            column_net: P011
        alt:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(7/2), 0]
            column_mark: 3
            column_net: P100
        left_arrow:
          key:
            shift: [u, 0]
            column_mark: 4
            column_net: P022
        down_arrow:
          key:
            shift: [u, 0]
            column_mark: 5
            column_net: P020
        right_arrow:
          key:
            shift: [u, 0]
            column_mark: 6
            column_net: P017
      rows:
        modrow:
          row_net: P113
outlines:
  2u_stabilizer:
    - operation: stack
      where: enterrow_enter_home
      what: rectangle
      size: [stabilizer_width, stabilizer_height]
      adjust:
        shift: [stabilizer_spacing_2u, stabilizer_offset]
    - operation: stack
      where: enterrow_enter_home
      what: rectangle
      size: [stabilizer_width, stabilizer_height]
      adjust:
        shift: [-stabilizer_spacing_2u, stabilizer_offset]
  raw:
    - what: rectangle
      where: true
      asym: left
      size: [1cx,1cy]
  keys:
    - what: rectangle
      where: true
      size: [cx-0.5, cy-0.5]
  keys_w_stabs:
    - name: keys
    - operation: add
      name: 2u_stabilizer
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_one_num
          shift: [-0.5px, 0.75py]
        - ref: matrix_eight_num
          shift: [1.75px, 0.75py]
        - ref: modrow_right_arrow_modrow
          shift: [1.75px, -0.75py]
        - ref: modrow_space_modrow
          shift: [-0.61px, -0.75py]
  combo:
    - name: board
    - operation: subtract
      name: keys_w_stabs
      
pcbs:
  aurora_r:
    outlines:
      main:
        outline: board
    footprints:
      mx-hotswap:
        what: mx
        where: true
        params:
          from: "{{colrow}}"
          to: "{{column_net}}"
          keycaps: true
          hotswap: true
      diode:
        what: diode
        where: true
        adjust:
          rotate: 0
          shift: [ 0, -10 ]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          # via_in_pad: true
          # through_hole: false
      rgb_led_even:
        what: WS2812-2020
        where: [/^(matrix_.*_num).*/, /^(enterrow_.*_home).*/, /^(modrow_.*_modrow).*/]
        adjust:
          shift: [ 0, -5 ]
        params:
          din: "P010"
          vcc: "VCC"
          dout: "P009"
          gnd: "GND"
      rgb_led_rotate_odd:
        what: WS2812-2020
        where: [/^(matrix_.*_top).*/, /^(bottomrow_.*_bottom).*/]
        adjust:
          rotate: 90
          shift: [ 0, -5 ]
        params:
          din: "P010"
          vcc: "VCC"
          dout: "P009"
          gnd: "GND"
      nice_nano:
        what: nice_nano
        where:
          ref: matrix_eight_num
          shift: [1.3u, -0.15u]
          rotate: -90
        params:
          orientation: up
      rotary:
        what: rotary
        params:
          A: P006
          B: GND
          C: P008
        where:
          ref: matrix_eight_top
          shift: [1.4u, -1u]
      nice_view:
        what: nice_view
        where:
          ref: matrix_eight_top
          rotate: -90
          shift: [1.4u, -1.5u]
        params:
          SDA: P107
          SCL: P102
          CS: P101
      powerswitch:
        what: slider
        where:
          ref: matrix_eight_top
          rotate: 270
          shift: [1.92u, -1.5u]
        params:
          from: RAW
          to: BAT
          side: B
      reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_eight_top
          rotate: 270
          shift: [1.92u, -0.25u]
      jstph:
        what: jstph
        where:
          ref: matrix_eight_top
          shift: [1.8u, -0.75u]
        params:
          pos: BAT
          neg: GND
          side: B
      hole_top_left:
        what: mountinghole
        where:
          ref: matrix_one_num
          shift: [0.5u, -0.5u]
      hole_top_right:
        what: mountinghole
        where:
          ref: matrix_eight_num
          shift: [-0.5u, -0.5u]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: bottomrow_one_bottom
          shift: [0.5u, 0.5u]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: bottomrow_eight_bottom
          shift: [-0.5u, -0.5u]
cases:
  top_plate:
    - name: combo
      extrude: 1.2
