
units:
  visual_x: 17.5
  visual_y: 16.5
  mod_x_width: 1.25cx
  px: cx + 4
  py: cy + 4

  # Stabalizer cutout
  u: U # Ensure we are using 19.05!
  stabilizer_width: 7
  stabilizer_height: 14
  stabilizer_offset: -1 # This means south stabs, use `orient` to rotate them for north facing scenarios
  stabilizer_spacing_2u: u / 2 + stabilizer_width / 2 + ((23.8 / 2) - (14 / 2) - (stabilizer_width / 2)) # The complex formula has two magic numbers. 14 is the size of a switch cutout for a plate. 23.8 is the distance between each stabilizer on a 2-2.75u stabilizer, as specified by Cherry

points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      columns:
        one:
          key:
            column_mark: 1
            column_net: P020
        two:
          key:
            spread: 1cx
            column_mark: 2
            column_net: P022
        three:
          key:
            spread: 1cx
            column_mark: 3
            column_net: P024
        four:
          key:
            spread: 1cx
            column_mark: 4
            column_net: P100
        five:
          key:
            spread:  1cx
            column_mark: 5
            column_net: P011
        six:
          key:
            spread:  1cx
            column_mark: 6
            column_net: P017
      rows:
        bottom:
          padding: 1cy
          row_net: P113
        home:
          padding: 1cy
          row_net: P115
        top:
          padding: 1cy
          row_net: P002
        num:
          padding: 1cy
          row_net: P029
    
    modrow:
      anchor:
        shift: [100, -100]
      key:
        padding: 1cy
        spread: 1cx
      columns:
        ctrl:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)/2, -1cy]
            column_mark: 1
            column_net: P020
        super:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(3/2), -1cy]
            column_mark: 2
            column_net: P022
        alt:
          key:
            width: mod_x_width
            shift: [(mod_x_width-1cx)*(5/2), -1cy]
            column_mark: 3
            column_net: P024
        space:
          key:
            width: 2.25cx
            shift: [(2.25cx-1cx)+(mod_x_width-1cx)/2, -1cy]
            column_mark: 5
            column_net: P011
      rows:
        modrow:
          row_net: P031
outlines:
  2u_stabilizer:
    - operation: stack
      where: modrow_space_modrow
      what: rectangle
      size: [stabilizer_width, stabilizer_height]
      adjust:
        shift: [stabilizer_spacing_2u, stabilizer_offset]
    - operation: stack
      where: modrow_space_modrow
      what: rectangle
      size: [stabilizer_width, stabilizer_height]
      adjust:
        shift: [-stabilizer_spacing_2u, stabilizer_offset]
  raw:
    - what: rectangle
      where: true
      asym: left
      size: [1cx,1cy]
  keys:
    - what: rectangle
      where: true
      size: [cx-0.5, cy-0.5]
  keys_w_stabs:
    - name: keys
    - operation: add
      name: 2u_stabilizer
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_one_num
          shift: [-0.75px, 1.7py]
        - ref: matrix_six_num
          shift: [0.5px, 1.7py]
        - ref: modrow_space_modrow
          shift: [1px, -0.5py]
        - ref: modrow_ctrl_modrow
          shift: [-0.875px,-0.5py]
  combo:
    - name: board
    - operation: subtract
      name: keys_w_stabs
      
pcbs:
  aurora_l:
    outlines:
      main:
        outline: board
    footprints:
      mx-hotswap:
        what: mx
        where: true
        params:
          from: "{{colrow}}"
          to: "{{column_net}}"
          keycaps: true
          hotswap: true
      diode:
        what: diode
        where: true
        adjust:
          rotate: 0
          shift: [ 0, -8 ]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          # via_in_pad: true
          # through_hole: false
      rgb_led_even:
        what: WS2812-2020
        where: [/^(matrix_.*_num).*/, /^(matrix_.*_home).*/, /^(modrow).*/]
        adjust:
          shift: [ 0, -5 ]
        params:
          din: "P8"
          vcc: "VCC"
          dout: "P15"
          gnd: "GND"
      rgb_led_rotate_odd:
        what: WS2812-2020
        where: [/^(matrix_.*_top).*/, /^(matrix_.*_bottom).*/]
        adjust:
          rotate: -90
          shift: [ 0, -5 ]
        params:
          din: "P8"
          vcc: "VCC"
          dout: "P15"
          gnd: "GND"
      nice_nano:
        what: nice_nano
        where:
          ref: matrix_one_num
          shift: [0.15cx, 1.2cy]
        params:
          orientation: up
      nice_view:
        what: nice_view
        where:
          ref: matrix_three_num
          shift: [1.3cx, 1.45cy]
        params:
          SDA: P017
          SCL: P020
          CS: P006
      powerswitch:
        what: slider
        where:
          ref: matrix_one_num
          shift: [-0.3cx, 1.94cy]
        params:
          from: RAW
          to: BAT
          side: B
      reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_one_num
          shift: [1cx, 1.94cy]
      jstph:
        what: jstph
        where:
          ref: matrix_one_num
          shift: [0.4cx, 1.9cy]
          rotate: -90
        params:
          pos: BAT
          neg: GND
          side: B
      hole_top_center:
        what: mountinghole
        where:
          ref: matrix_three_num
          shift: [0.7cx, 1.2cy]
      hole_top_right:
        what: mountinghole
        where:
          ref: matrix_six_num
          shift: [-0.3cx, 0.7cy]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: modrow_ctrl_modrow
          shift: [-0.8cx, -0.3cy]